name: Deploy to Amazon ECS

on:
  push:
    branches: [ "main" ]
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }} 
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  PRIVATE_SSH_KEY: ${{ secrets.AWS_SSH_KEY_PRIVATE }}
  PUBLIC_SSH_KEY: ${{ secrets.AWS_SSH_KEY_PUBLIC }}
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: dockerhub login
      uses: docker/login-action@v1
      with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}
    

    - name: Build the Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: talole84/nodejs:${{ github.sha }}


    - name: Deploy to Amazon EC2
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: nodejs
        IMAGE_TAG: ${{ github.sha }}
        AWS_DEFAULT_REGION: ap-south-1
      uses: appleboy/ssh-action@v0.1.10
      with: 
       host: ${{ secrets.SERVER_PUBLIC_IP }}
       username: ubuntu
       key: ${{ secrets.AWS_SSH_KEY_PRIVATE }}
       scripts: |-
         sudo docker stop nodejs || true
         sudo docker rm nodejs || true
         sudo docker pull ${{ secrets.DOCKER_USERNAME }}/nodejs:${{ github.sha }}
         sudo docker run --d --name nodejs -p 80:3000 ${{ secrets.DOCKER_USERNAME }}/nodejs:${{ github.sha }}
